# Generated by Django 4.2 on 2023-04-12 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estorapp', '0002_product_slash_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_details',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_brifing',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
