# Generated by Django 4.2 on 2023-04-12 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estorapp', '0003_product_product_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_informations',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
    ]
