# Generated by Django 4.2 on 2023-04-16 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estorapp', '0004_product_product_informations'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='country',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='order_note',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='post_code',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='state',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
