# Generated by Django 4.2 on 2023-04-16 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estorapp', '0005_delivery_country_delivery_order_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='email',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='first_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='last_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
