# Generated by Django 4.2 on 2023-04-16 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estorapp', '0006_delivery_email_delivery_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='apartment',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
